/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bean.Etudiant;
import bean.Filiere;
import controller.AnneeController;
import controller.EtudiantController;
import controller.FiliereController;
import controller.NationaliteController;
import controller.NiveauController;
import controller.OptionController;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author ATH
 */
public class EtudiantDialog extends javax.swing.JDialog {

    /**
     * Creates new form Eleve
     * @param parent
     * @param modal
     */
    public EtudiantDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        etudiantController = new EtudiantController();
        nationaliteController = new NationaliteController();
        filiereController = new FiliereController();
        optionController = new OptionController();
        anneeController = new AnneeController();
        niveauController = new NiveauController();
        initComponents();
        initCbAnnee();
        initCbNiveau();
        initCbFiliere();
        initCbOption();
        initCbNationalite();
    }
    
    public EtudiantDialog(java.awt.Frame parent, boolean modal, Etudiant etudiant) {
        super(parent, modal);
        etudiantController = new EtudiantController();
        nationaliteController = new NationaliteController();
        this.etudiant = etudiant;
        filiereController = new FiliereController();
        optionController = new OptionController();
        anneeController = new AnneeController();
        niveauController = new NiveauController();
        initComponents();
        initCbAnnee();
        initCbNiveau();
        initCbFiliere();
        initCbOption();
        initCbNationalite();
        try {
            rSComboMetro_annee.setSelectedItem(anneeController.getAnnee(this.etudiant.getId_annee()).getAnnee());
            rSComboMetro_filiere.setSelectedItem(filiereController.getFiliere(optionController.getOption(this.etudiant.getId_option()).getId_filiere()).getFiliere());
            rSComboMetro_option.setSelectedItem(optionController.getOption(this.etudiant.getId_option()).getOption());
            rSbComboMetro_nationalite.setSelectedItem(nationaliteController.getNationalite(this.etudiant.getId_nationalite()));
            rSComboMetro_sexe.setSelectedItem(etudiant.getSexe());
            if(this.etudiant.getPhoto() != null){
                jLabel_photo.setIcon(new ImageIcon(this.etudiant.getPhoto()));
            }
        } catch (Exception e) {
        }
        
        rSMTextFull_contact.setText(etudiant.getContact());
        rSMTextFull_nom_prenom.setText(etudiant.getNom_prenom());
        rSMTextFull_matricule.setText(etudiant.getMatricule());
        jDateChooser_date_de_naissance.setDate(etudiant.getDate_de_naissance());
        rSMTextFull_lieu_de_naissance.setText(etudiant.getLieu_de_naissance());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMTextFull_nom_prenom = new rojeru_san.RSMTextFull();
        rSMTextFull_contact = new rojeru_san.RSMTextFull();
        rSbComboMetro_nationalite = new rojerusan.RSComboMetro();
        btn_valider = new rojeru_san.RSButton();
        rSMTextFull_matricule = new rojeru_san.RSMTextFull();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser_date_de_naissance = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        rSMTextFull_lieu_de_naissance = new rojeru_san.RSMTextFull();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSComboMetro_sexe = new rojerusan.RSComboMetro();
        rSComboMetro_filiere = new rojerusan.RSComboMetro();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rSComboMetro_annee = new rojerusan.RSComboMetro();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rSComboMetro_option = new rojerusan.RSComboMetro();
        rSComboMetro_niveau = new rojerusan.RSComboMetro();
        jLabel_photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des étudiants");
        setResizable(false);

        rSMTextFull_nom_prenom.setPlaceholder("Nom et Prénom");

        rSMTextFull_contact.setToolTipText("");
        rSMTextFull_contact.setPlaceholder("Tel.");

        btn_valider.setText("Valider");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        rSMTextFull_matricule.setEditable(false);
        rSMTextFull_matricule.setPlaceholder("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Matricule");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nom et Prénom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Date de Naissance");

        rSMTextFull_lieu_de_naissance.setPlaceholder("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Lieu de Naissance");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nationalité");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Contact");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Sexe");

        rSComboMetro_sexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        rSComboMetro_filiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro_filiereActionPerformed(evt);
            }
        });

        jLabel8.setText("Filière");

        jLabel9.setText("Option");

        jLabel10.setText("Année scolaire");

        jLabel11.setText("Niveau :");

        jLabel_photo.setBackground(new java.awt.Color(51, 153, 255));
        jLabel_photo.setForeground(new java.awt.Color(0, 153, 204));
        jLabel_photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/approval.png"))); // NOI18N
        jLabel_photo.setToolTipText("Choisir une photo");
        jLabel_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_photo.setMaximumSize(new java.awt.Dimension(122, 118));
        jLabel_photo.setMinimumSize(new java.awt.Dimension(122, 118));
        jLabel_photo.setPreferredSize(new java.awt.Dimension(122, 118));
        jLabel_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_photoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSMTextFull_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rSbComboMetro_nationalite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser_date_de_naissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rSComboMetro_sexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rSMTextFull_lieu_de_naissance, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSMTextFull_nom_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSMTextFull_matricule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rSComboMetro_option, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rSComboMetro_filiere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rSComboMetro_annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rSComboMetro_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSComboMetro_annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(rSComboMetro_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSComboMetro_filiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSComboMetro_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMTextFull_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMTextFull_nom_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSMTextFull_lieu_de_naissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jDateChooser_date_de_naissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rSbComboMetro_nationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rSComboMetro_sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMTextFull_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        if(rSMTextFull_nom_prenom.getText().length() == 0 || rSMTextFull_contact.getText().length() == 0 || rSbComboMetro_nationalite.getSelectedIndex() <0 || rSMTextFull_matricule.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Champ vide.", "Erreur de syntaxe !", JOptionPane.WARNING_MESSAGE);
        }else{
            if(etudiant == null){
                Date date = new Date(jDateChooser_date_de_naissance.getDate().getTime());
                etudiantController.addEtudiant(
                        anneeController.getAnnee(rSComboMetro_annee.getSelectedItem().toString()).getId(),
                        nationaliteController.getNationalite(rSbComboMetro_nationalite.getSelectedItem().toString()).getId(),
                        optionController.getOption(filiereController.getFiliere(rSComboMetro_filiere.getSelectedItem().toString()).getId(), rSComboMetro_option.getSelectedItem().toString()).getId(),
                        niveauController.getNiveau(rSComboMetro_niveau.getSelectedItem().toString()).getId(),
                        rSMTextFull_matricule.getText(),
                        rSMTextFull_nom_prenom.getText(),
                        date,
                        rSMTextFull_lieu_de_naissance.getText(),
                        rSMTextFull_contact.getText(),
                        rSComboMetro_sexe.getSelectedItem().toString(),
                        photo,
                        null
                );
                
            }else{
                Date date = new Date(jDateChooser_date_de_naissance.getDate().getTime());
                etudiantController.updateEtudiant(
                        etudiant.getId(),
                        anneeController.getAnnee(rSComboMetro_annee.getSelectedItem().toString()).getId(),
                        nationaliteController.getNationalite(rSbComboMetro_nationalite.getSelectedItem().toString()).getId(),
                        optionController.getOption(filiereController.getFiliere(rSComboMetro_filiere.getSelectedItem().toString()).getId(), rSComboMetro_option.getSelectedItem().toString()).getId(),
                        niveauController.getNiveau(rSComboMetro_niveau.getSelectedItem().toString()).getId(),
                        rSMTextFull_matricule.getText(),
                        rSMTextFull_nom_prenom.getText(),
                        date,
                        rSMTextFull_lieu_de_naissance.getText(),
                        rSMTextFull_contact.getText(),
                        rSComboMetro_sexe.getSelectedItem().toString(),
                        photo,
                        null
                );
            }
            success_information();
            this.dispose();
        }
    }//GEN-LAST:event_btn_validerActionPerformed

    private void rSComboMetro_filiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro_filiereActionPerformed
        initCbOption();
    }//GEN-LAST:event_rSComboMetro_filiereActionPerformed

    private void jLabel_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_photoMouseClicked
        saving_image();
    }//GEN-LAST:event_jLabel_photoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudiantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            EtudiantDialog dialog = new EtudiantDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    private bean.Etudiant etudiant;
    private final EtudiantController etudiantController;
    private final NationaliteController nationaliteController;
    private final FiliereController filiereController;
    private final OptionController optionController;
    private final AnneeController anneeController;
    private final NiveauController niveauController;
    private String photo;
    private static String PHOTO_DIR = "C:/GesInstus/ressources/photo/";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btn_valider;
    private com.toedter.calendar.JDateChooser jDateChooser_date_de_naissance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_photo;
    private rojerusan.RSComboMetro rSComboMetro_annee;
    private rojerusan.RSComboMetro rSComboMetro_filiere;
    private rojerusan.RSComboMetro rSComboMetro_niveau;
    private rojerusan.RSComboMetro rSComboMetro_option;
    private rojerusan.RSComboMetro rSComboMetro_sexe;
    private rojeru_san.RSMTextFull rSMTextFull_contact;
    private rojeru_san.RSMTextFull rSMTextFull_lieu_de_naissance;
    private rojeru_san.RSMTextFull rSMTextFull_matricule;
    private rojeru_san.RSMTextFull rSMTextFull_nom_prenom;
    private rojerusan.RSComboMetro rSbComboMetro_nationalite;
    // End of variables declaration//GEN-END:variables

    private void initCbNationalite() {
        rSbComboMetro_nationalite.removeAllItems();
        nationaliteController.getNationalites().forEach((n) -> {
            rSbComboMetro_nationalite.addItem(n.getNationalite());
        });
    }
    private void initCbFiliere(){
        rSComboMetro_filiere.removeAllItems();
        filiereController.getFilieres().forEach((f) -> {
            rSComboMetro_filiere.addItem(f.getFiliere());
        });
        initMatricule();
    }
    private void initCbOption(){
        rSComboMetro_option.removeAllItems();
        if(rSComboMetro_filiere.getSelectedIndex() < 0){
            return;
        }
        Filiere filiere = filiereController.getFiliere(rSComboMetro_filiere.getSelectedItem().toString());
        if(filiere == null){
            return;
        }
        optionController.getOptions(filiere.getId()).forEach((o) -> {
            rSComboMetro_option.addItem(o.getOption());
        });
        initMatricule();
    }
    private void initMatricule(){
        if(rSComboMetro_filiere.getSelectedIndex() < 0 || rSComboMetro_option.getSelectedIndex() < 0){
            rSMTextFull_matricule.setText("");
            return;
        }
        String filiere = rSComboMetro_filiere.getSelectedItem().toString();
//        int rang = etudiantController.getMaxID() + 1;
        int rang = 1;
        String matricule = String.format("%03d", rang) + "/" + filiereController.getFiliere(filiere).getSigle();
        while(etudiantController.getEtudiant(matricule) != null){
            rang++;
            matricule = String.format("%03d", rang) + "/" + filiereController.getFiliere(filiere).getSigle();
        }
        rSMTextFull_matricule.setText(matricule);
    }

    private void initCbAnnee() {
        rSComboMetro_annee.removeAllItems();
        anneeController.getAnnees().forEach((a) -> {
            rSComboMetro_annee.addItem(a.getAnnee());
        });
    }
    private void initCbNiveau(){
        rSComboMetro_niveau.removeAllItems();
        niveauController.getNiveaux().forEach((n) -> {
            rSComboMetro_niveau.addItem(n.getNiveau());
        });
        initMatricule();
    }
    
    private void saving_image() {
        JFileChooser fileChooser = new JFileChooser();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        fileChooser.setDialogTitle("Choisir la photo");
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Image files", new String[] { "png", "jpg", "jpeg" }));
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        try {
          Image image = ImageIO.read(fileChooser.getSelectedFile());
          File source = new File(fileChooser.getSelectedFile().getAbsolutePath());
          if (image != null) {
            String extension = FilenameUtils.getExtension(fileChooser.getSelectedFile().getName());
            File des = new File(PHOTO_DIR + rSMTextFull_matricule.getText().replaceAll("/", "-") + "." + extension);
            FileUtils.copyFile(source, des);
            photo = PHOTO_DIR + rSMTextFull_matricule.getText().replaceAll("/", "-") + "." + extension;
            if(photo != null){
                jLabel_photo.setIcon(new ImageIcon(photo));
            }
          }
        } catch (IOException ex) {
        }
      }
    }
    private void success_information() {
        JOptionPane.showMessageDialog(this, "Opération effectuée avec succes ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
    }
}
