/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import controller.AnneeController;
import controller.NationaliteController;
import controller.ParametreController;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import rojerusan.RSPanelImage;
import view.dialog.AnneeDialog;
import view.dialog.NationaliteDialog;

/**
 *
 * @author ATH
 */
public class ConfigPanel extends RSPanelImage {

    /**
     * Creates new form ElevePan
     */
    public ConfigPanel() {
        anneeController = new AnneeController();
        nationaliteController = new NationaliteController();
        parametreController = new ParametreController();
        initComponents();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_menu_list_annee = new javax.swing.JPopupMenu();
        menu_item_add_annee = new javax.swing.JMenuItem();
        menu_item_update_annee = new javax.swing.JMenuItem();
        menu_item_remove_annee = new javax.swing.JMenuItem();
        menu_item_select_annee = new javax.swing.JMenuItem();
        popup_menu_list_nationalite = new javax.swing.JPopupMenu();
        menu_item_add_nationalite = new javax.swing.JMenuItem();
        menu_item_update_nationalite = new javax.swing.JMenuItem();
        menu_item_remove_nationalite = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_annee_scolaire = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel_annee_en_cours = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_nationalite = new javax.swing.JList<>();

        menu_item_add_annee.setText("Ajouter une nouvelle année");
        menu_item_add_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_add_anneeActionPerformed(evt);
            }
        });
        popup_menu_list_annee.add(menu_item_add_annee);

        menu_item_update_annee.setText("Modifier l'année");
        menu_item_update_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_update_anneeActionPerformed(evt);
            }
        });
        popup_menu_list_annee.add(menu_item_update_annee);

        menu_item_remove_annee.setText("Retirer l'année");
        menu_item_remove_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_remove_anneeActionPerformed(evt);
            }
        });
        popup_menu_list_annee.add(menu_item_remove_annee);

        menu_item_select_annee.setText("Choisir comme année scolaire");
        menu_item_select_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_select_anneeActionPerformed(evt);
            }
        });
        popup_menu_list_annee.add(menu_item_select_annee);

        menu_item_add_nationalite.setText("Ajouter une nationalité");
        menu_item_add_nationalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_add_nationaliteActionPerformed(evt);
            }
        });
        popup_menu_list_nationalite.add(menu_item_add_nationalite);

        menu_item_update_nationalite.setText("Modifier la nationalité");
        menu_item_update_nationalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_update_nationaliteActionPerformed(evt);
            }
        });
        popup_menu_list_nationalite.add(menu_item_update_nationalite);

        menu_item_remove_nationalite.setText("Retirer la nationalité");
        menu_item_remove_nationalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_remove_nationaliteActionPerformed(evt);
            }
        });
        popup_menu_list_nationalite.add(menu_item_remove_nationalite);

        setImagen(new javax.swing.ImageIcon(getClass().getResource("/icon/getty_655998316_2000149920009280219_363765.jpg"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 579));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Liste des Années scolaires", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jList_annee_scolaire.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList_annee_scolaire.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_annee_scolaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jList_annee_scolaireMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList_annee_scolaire);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Droit de saisir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton1.setText("Suppression");

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton2.setText("Ajout");

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton3.setText("Modification");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToggleButton3))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_annee_en_cours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_annee_en_cours.setText("Année scolaire :");

        jList_nationalite.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Liste des nationalités", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jList_nationalite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList_nationalite.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_nationalite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jList_nationaliteMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jList_nationalite);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_annee_en_cours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_annee_en_cours, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_add_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_add_anneeActionPerformed
        AnneeDialog annee = new AnneeDialog(null, true);
        annee.setVisible(true);
        update();
    }//GEN-LAST:event_menu_item_add_anneeActionPerformed

    private void menu_item_update_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_update_anneeActionPerformed
        AnneeDialog annee = new AnneeDialog(null, true, anneeController.getAnnee(jList_annee_scolaire.getSelectedValue()));
        annee.setVisible(true);
        update();
    }//GEN-LAST:event_menu_item_update_anneeActionPerformed

    private void menu_item_remove_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_remove_anneeActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer l'année " + jList_annee_scolaire.getSelectedValue() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            anneeController.removeAnnee(anneeController.getAnnee(jList_annee_scolaire.getSelectedValue()).getId());
            success_information();
        }
        update();
    }//GEN-LAST:event_menu_item_remove_anneeActionPerformed

    private void menu_item_select_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_select_anneeActionPerformed
        parametreController.updateParametre(anneeController.getAnnee(jList_annee_scolaire.getSelectedValue()).getId());
        update();
    }//GEN-LAST:event_menu_item_select_anneeActionPerformed

    private void menu_item_add_nationaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_add_nationaliteActionPerformed
        NationaliteDialog nationalite = new NationaliteDialog(null, true);
        nationalite.setVisible(true);
        update();
    }//GEN-LAST:event_menu_item_add_nationaliteActionPerformed

    private void menu_item_update_nationaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_update_nationaliteActionPerformed
        NationaliteDialog nationalite = new NationaliteDialog(null, true, nationaliteController.getNationalite(jList_nationalite.getSelectedValue()));
        nationalite.setVisible(true);
        update();
    }//GEN-LAST:event_menu_item_update_nationaliteActionPerformed

    private void menu_item_remove_nationaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_remove_nationaliteActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer la nationalité " + jList_nationalite.getSelectedValue() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            nationaliteController.removeNationalite(nationaliteController.getNationalite(jList_nationalite.getSelectedValue()).getId());
        }
        update();
    }//GEN-LAST:event_menu_item_remove_nationaliteActionPerformed

    private void jList_annee_scolaireMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_annee_scolaireMouseReleased
        int index = jList_annee_scolaire.getSelectedIndex();
        menu_item_remove_annee.setEnabled(true);
        menu_item_update_annee.setEnabled(true);
        menu_item_select_annee.setEnabled(true);
        if(index < 0){
            menu_item_remove_annee.setEnabled(false);
            menu_item_update_annee.setEnabled(false);
            menu_item_select_annee.setEnabled(false);
        }
        if(evt.isPopupTrigger() && evt.getComponent() instanceof JList){
            popup_menu_list_annee.show(evt.getComponent(), evt.getX(), evt.getY());
            popup_menu_list_annee.setVisible(true);
        }
    }//GEN-LAST:event_jList_annee_scolaireMouseReleased

    private void jList_nationaliteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_nationaliteMouseReleased
        int index = jList_nationalite.getSelectedIndex();
        menu_item_remove_nationalite.setEnabled(true);
        menu_item_update_nationalite.setEnabled(true);
        if(index < 0){
            menu_item_remove_nationalite.setEnabled(false);
            menu_item_update_nationalite.setEnabled(false);
        }
        if(evt.isPopupTrigger() && evt.getComponent() instanceof JList){
            popup_menu_list_nationalite.show(evt.getComponent(), evt.getX(), evt.getY());
            popup_menu_list_nationalite.setVisible(true);
        }
    }//GEN-LAST:event_jList_nationaliteMouseReleased

    private final AnneeController anneeController;
    private final NationaliteController nationaliteController;
    private final ParametreController parametreController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_annee_en_cours;
    private javax.swing.JList<String> jList_annee_scolaire;
    private javax.swing.JList<String> jList_nationalite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JMenuItem menu_item_add_annee;
    private javax.swing.JMenuItem menu_item_add_nationalite;
    private javax.swing.JMenuItem menu_item_remove_annee;
    private javax.swing.JMenuItem menu_item_remove_nationalite;
    private javax.swing.JMenuItem menu_item_select_annee;
    private javax.swing.JMenuItem menu_item_update_annee;
    private javax.swing.JMenuItem menu_item_update_nationalite;
    private javax.swing.JPopupMenu popup_menu_list_annee;
    private javax.swing.JPopupMenu popup_menu_list_nationalite;
    // End of variables declaration//GEN-END:variables

    private void update_list_annee() {
        jList_annee_scolaire.setModel(new javax.swing.AbstractListModel<String>() {
        ArrayList<bean.Annee> strings = anneeController.getAnnees();
        @Override
            public int getSize() { return strings.size(); }
        @Override
            public String getElementAt(int i) { return strings.get(i).getAnnee(); }
        });
    }
    
    
    private void success_information() {
        JOptionPane.showMessageDialog(this, "Opération effectuée avec succes ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
    }

    private void update_label_annee_scolaire(){
        if(parametreController.getParametre()== null){
            return;
        }
        jLabel_annee_en_cours.setText("Année en cours : " + anneeController.getAnnee(parametreController.getParametre().getId_annee()).getAnnee());
    }

    private void update_list_nationalite() {
        jList_nationalite.setModel(new javax.swing.AbstractListModel<String>() {
        ArrayList<bean.Nationalite> strings = nationaliteController.getNationalites();
        @Override
            public int getSize() { return strings.size(); }
        @Override
            public String getElementAt(int i) { return strings.get(i).getNationalite(); }
        });
    }
    
    private void update(){
        update_list_annee();
        update_label_annee_scolaire();
        update_list_nationalite();
    }
}
