/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import bean.Filiere;
import bean.Niveau;
import bean.Option;
import bean.Semestre;
import bean.UniteEnseignement;
import bean.UniteEnseignementOptionTable;
import controller.FiliereController;
import controller.NiveauController;
import controller.OptionController;
import controller.SemestreController;
import controller.UniteEnseignementController;
import controller.UniteEnseignementOptionController;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSPanelImage;
import view.dialog.UniteEnseignementOptionDialog;

/**
 *
 * @author ATH
 */
public class UniteEnseignementOptionPanel extends RSPanelImage {

    /**
     * Creates new form ElevePan
     */
    public UniteEnseignementOptionPanel() {
        filiereController = new FiliereController();
        semestreController = new SemestreController();
        uniteEnseignementOptionController = new UniteEnseignementOptionController();
        optionController = new OptionController();
        niveauController = new NiveauController();
        uniteEnseignementController = new UniteEnseignementController();
        initComponents();
        initCbNiveau();
        initCbSemestre();
        initCbFiliere();
        initCbOption();
        update_table_ueo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_table_ue = new javax.swing.JPopupMenu();
        menu_item_add_ue = new javax.swing.JMenuItem();
        menu_item_update_ue = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_item_remove_ue = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_ue = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        rSMTextFull_rechercher = new rojeru_san.RSMTextFull();
        rSComboMetro_niveau = new rojerusan.RSComboMetro();
        rSComboMetro_semestre = new rojerusan.RSComboMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSComboMetro_filiere = new rojerusan.RSComboMetro();
        rSComboMetro_options = new rojerusan.RSComboMetro();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        menu_item_add_ue.setText("Attribuer une nouvelle unité d'enseignement pour une option");
        menu_item_add_ue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_add_ueActionPerformed(evt);
            }
        });
        popup_table_ue.add(menu_item_add_ue);

        menu_item_update_ue.setText("Modifier l'unité d'enseignement de cette option");
        menu_item_update_ue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_update_ueActionPerformed(evt);
            }
        });
        popup_table_ue.add(menu_item_update_ue);
        popup_table_ue.add(jSeparator1);

        menu_item_remove_ue.setText("Retirer l'unité d'enseignemant de cette option");
        menu_item_remove_ue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_remove_ueActionPerformed(evt);
            }
        });
        popup_table_ue.add(menu_item_remove_ue);

        setImagen(new javax.swing.ImageIcon(getClass().getResource("/icon/getty_655998316_2000149920009280219_363765.jpg"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 579));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 102, 102)), "Liste des unités d'enseignemants par option", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseReleased(evt);
            }
        });

        jTable_ue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "FILIERE", "SEMESTRE", "SIGLE", "UNITE D'ENSEIGNEMANT", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ueMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable_ueMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_ue);
        if (jTable_ue.getColumnModel().getColumnCount() > 0) {
            jTable_ue.getColumnModel().getColumn(0).setMinWidth(50);
            jTable_ue.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable_ue.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_ue.getColumnModel().getColumn(1).setMinWidth(300);
            jTable_ue.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable_ue.getColumnModel().getColumn(1).setMaxWidth(300);
            jTable_ue.getColumnModel().getColumn(2).setMinWidth(100);
            jTable_ue.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable_ue.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable_ue.getColumnModel().getColumn(3).setMinWidth(75);
            jTable_ue.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTable_ue.getColumnModel().getColumn(3).setMaxWidth(75);
            jTable_ue.getColumnModel().getColumn(5).setMinWidth(10);
            jTable_ue.getColumnModel().getColumn(5).setPreferredWidth(10);
            jTable_ue.getColumnModel().getColumn(5).setMaxWidth(10);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Filtrage table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        rSMTextFull_rechercher.setPlaceholder("Rechercher");
        rSMTextFull_rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSMTextFull_rechercherKeyReleased(evt);
            }
        });

        rSComboMetro_niveau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rSComboMetro_niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro_niveauActionPerformed(evt);
            }
        });

        rSComboMetro_semestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro_semestreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Semestre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Niveau");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSMTextFull_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSComboMetro_semestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSComboMetro_niveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSMTextFull_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSComboMetro_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rSComboMetro_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        rSComboMetro_filiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro_filiereActionPerformed(evt);
            }
        });

        rSComboMetro_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro_optionsActionPerformed(evt);
            }
        });

        jLabel8.setText("Filière");

        jLabel9.setText("Option");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSComboMetro_filiere, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(rSComboMetro_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSComboMetro_filiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSComboMetro_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_add_ueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_add_ueActionPerformed
        UniteEnseignementOptionDialog ueod = new UniteEnseignementOptionDialog(null, true);
        ueod.setVisible(true);
        update_table_ueo();
    }//GEN-LAST:event_menu_item_add_ueActionPerformed

    private void menu_item_update_ueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_update_ueActionPerformed
        int row = jTable_ue.getSelectedRow();
        int id = Integer.parseInt(jTable_ue.getValueAt(row, 5).toString());
        UniteEnseignementOptionDialog ueod = new UniteEnseignementOptionDialog(null, true, uniteEnseignementOptionController.getUniteEnseignementOption(id));
        ueod.setVisible(true);
        update_table_ueo();
    }//GEN-LAST:event_menu_item_update_ueActionPerformed

    private void menu_item_remove_ueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_remove_ueActionPerformed
        int row = jTable_ue.getSelectedRow();
        int id = Integer.parseInt(jTable_ue.getValueAt(row, 5).toString());
        String option = optionController.getOption(uniteEnseignementOptionController.getUniteEnseignementOption(id).getId_option()).getOption();
        int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer l'unité d'enseignemant " + jTable_ue.getValueAt(row, 4) + " de l'option " + option + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            uniteEnseignementOptionController.removeUniteEnseignementOption(id);
        }
        update_table_ueo();
    }//GEN-LAST:event_menu_item_remove_ueActionPerformed

    private void jScrollPane3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseReleased
        action_popup_menu_ueo(evt);
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JScrollPane) {
            popup_table_ue.show(evt.getComponent(), evt.getX(), evt.getY());
            popup_table_ue.setVisible(true);
        }
    }//GEN-LAST:event_jScrollPane3MouseReleased

    private void jTable_ueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ueMouseReleased
        action_popup_menu_ueo(evt);
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable) {
            popup_table_ue.show(evt.getComponent(), evt.getX(), evt.getY());
            popup_table_ue.setVisible(true);
        }
    }//GEN-LAST:event_jTable_ueMouseReleased

    private void rSComboMetro_niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro_niveauActionPerformed
        initCbSemestre();
        update_table_ueo();
    }//GEN-LAST:event_rSComboMetro_niveauActionPerformed

    private void rSComboMetro_semestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro_semestreActionPerformed
        update_table_ueo();
    }//GEN-LAST:event_rSComboMetro_semestreActionPerformed

    private void rSComboMetro_filiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro_filiereActionPerformed
        initCbOption();
        update_table_ueo();
    }//GEN-LAST:event_rSComboMetro_filiereActionPerformed

    private void rSComboMetro_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro_optionsActionPerformed
        update_table_ueo();
    }//GEN-LAST:event_rSComboMetro_optionsActionPerformed

    private void jTable_ueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ueMouseClicked
        //update_table_ueo();
    }//GEN-LAST:event_jTable_ueMouseClicked

    private void rSMTextFull_rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSMTextFull_rechercherKeyReleased
        update_table_ueo();
    }//GEN-LAST:event_rSMTextFull_rechercherKeyReleased

    private final FiliereController filiereController;
    private final SemestreController semestreController;
    private final UniteEnseignementOptionController uniteEnseignementOptionController;
    private final UniteEnseignementController uniteEnseignementController;
    private final OptionController optionController;
    private final NiveauController niveauController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable_ue;
    private javax.swing.JMenuItem menu_item_add_ue;
    private javax.swing.JMenuItem menu_item_remove_ue;
    private javax.swing.JMenuItem menu_item_update_ue;
    private javax.swing.JPopupMenu popup_table_ue;
    private rojerusan.RSComboMetro rSComboMetro_filiere;
    private rojerusan.RSComboMetro rSComboMetro_niveau;
    private rojerusan.RSComboMetro rSComboMetro_options;
    private rojerusan.RSComboMetro rSComboMetro_semestre;
    private rojeru_san.RSMTextFull rSMTextFull_rechercher;
    // End of variables declaration//GEN-END:variables

    private void initCbFiliere() {
        rSComboMetro_filiere.removeAllItems();
        filiereController.getFilieres().forEach((f) -> {
            rSComboMetro_filiere.addItem(f.getFiliere());
        });
        if (rSComboMetro_filiere.getItemCount() > 1) {
            rSComboMetro_filiere.addItem("Toutes");
        }

    }
    private void initCbOption() {
        rSComboMetro_options.removeAllItems();
        int id_filiere = 0;
        Filiere filiere = filiereController.getFiliere(rSComboMetro_filiere.getSelectedItem().toString());
        if(filiere != null){
            id_filiere = filiere.getId();
        }
        optionController.getOptions(id_filiere).forEach((o) -> {
            rSComboMetro_options.addItem(o.getOption());
        });
        if(rSComboMetro_options.getItemCount() > 1){
            rSComboMetro_options.addItem("Toutes");
        }
    }

    private void initCbNiveau() {
        rSComboMetro_niveau.removeAllItems();
        niveauController.getNiveaux().forEach((n) -> {
            rSComboMetro_niveau.addItem(n.getNiveau());
        });
        if (rSComboMetro_niveau.getItemCount() > 1) {
            rSComboMetro_niveau.addItem("Tous");
        }
    }

    private void initCbSemestre() {
        rSComboMetro_semestre.removeAllItems();
        int id_niveau = 0;
        if(rSComboMetro_niveau.getSelectedIndex() > -1){
            Niveau niveau = niveauController.getNiveau(rSComboMetro_niveau.getSelectedItem().toString());
            if(niveau != null){
                id_niveau = niveau.getId();
            }
        }
        semestreController.getSemestres(id_niveau).forEach((s) -> {
            rSComboMetro_semestre.addItem(s.getSemestre());
        });
        if (rSComboMetro_semestre.getItemCount() > 1) {
            rSComboMetro_semestre.addItem("Toutes");
        }
    }
    private void update_table_ueo() {
        String entete[] = {"N°", "FILIERE/OPTION", "SEMESTRE", "SIGLE", "UNITE D'ENSEIGNEMANT", "ID"};
        DefaultTableModel dt = new DefaultTableModel(null, entete);
        dt.setRowCount(0);
        
        String rechercher = null;
        int id_option = 0, id_semestre = 0;
        if(rSMTextFull_rechercher.getText().length() > 0){
            rechercher = rSMTextFull_rechercher.getText();
        }
        if(rSComboMetro_options.getSelectedIndex() > -1 && rSComboMetro_filiere.getSelectedIndex() > -1){
            Option option = optionController.getOption(filiereController.getFiliere(rSComboMetro_filiere.getSelectedItem().toString()).getId(), rSComboMetro_options.getSelectedItem().toString());
            if(option != null){
                id_option = option.getId();
            }
        }
        if(rSComboMetro_semestre.getSelectedIndex() > -1){
            Semestre semestre = semestreController.getSemestre(rSComboMetro_semestre.getSelectedItem().toString());
            if(semestre != null){
                id_semestre = semestre.getId();
            }
        }
        
        ArrayList<UniteEnseignementOptionTable> list = uniteEnseignementOptionController.getUniteEnseignementOptionTables(id_option, id_semestre, rechercher);
        
        for (int i = 0; i < list.size(); i++) {
            System.out.println("id_filiere : " + list.get(i).getId_filiere());
            System.out.println("id_option : " + list.get(i).getId_option());
            System.out.println("id_unite_enseignement : " + list.get(i).getId_unite_enseignement());
            System.out.println("id : " + list.get(i).getId());
            Object colonne[] = new Object[6];
            colonne[0] = i + 1;
            colonne[1] = filiereController.getFiliere(list.get(i).getId_filiere()).getFiliere() + " / " + optionController.getOption(list.get(i).getId_option()).getOption();
            colonne[2] = semestreController.getSemestre(list.get(i).getId_semestre()).getSemestre();
            UniteEnseignement uniteEnseignement = uniteEnseignementController.getUniteEnseignement(list.get(i).getId_unite_enseignement());
            colonne[3] = uniteEnseignement == null ? "" : uniteEnseignement.getSigle();
            colonne[4] = uniteEnseignement == null ? "" : uniteEnseignement.getNom();
            colonne[5] = list.get(i).getId();
            dt.addRow(colonne);
        }
        this.jTable_ue.setModel(dt);
        if (jTable_ue.getColumnModel().getColumnCount() > 0) {
            jTable_ue.getColumnModel().getColumn(0).setMinWidth(50);
            jTable_ue.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable_ue.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_ue.getColumnModel().getColumn(1).setMinWidth(400);
            jTable_ue.getColumnModel().getColumn(1).setPreferredWidth(400);
            jTable_ue.getColumnModel().getColumn(1).setMaxWidth(400);
            jTable_ue.getColumnModel().getColumn(2).setMinWidth(100);
            jTable_ue.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable_ue.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable_ue.getColumnModel().getColumn(3).setMinWidth(75);
            jTable_ue.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTable_ue.getColumnModel().getColumn(3).setMaxWidth(75);
            jTable_ue.getColumnModel().getColumn(5).setMinWidth(5);
            jTable_ue.getColumnModel().getColumn(5).setPreferredWidth(5);
            jTable_ue.getColumnModel().getColumn(5).setMaxWidth(5);
            jTable_ue.setRowHeight(30);
        }
        jTable_ue.getTableHeader().setBackground(new Color(0,112,192));
        jTable_ue.getTableHeader().setForeground(Color.white);
        jTable_ue.getTableHeader().setFont(new Font("Cambria Math", Font.BOLD, 13));
    }
    
    private void action_popup_menu_ueo(java.awt.event.MouseEvent evt) {
        int r = jTable_ue.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < jTable_ue.getRowCount()) {
            jTable_ue.setRowSelectionInterval(r, r);

        } else {
            jTable_ue.clearSelection();
        }
        int index = jTable_ue.getSelectedRow();
        if (index < 0) {
            menu_item_remove_ue.setEnabled(false);
            menu_item_update_ue.setEnabled(false);
        } else {
            menu_item_add_ue.setEnabled(true);
            menu_item_remove_ue.setEnabled(true);
            menu_item_update_ue.setEnabled(true);
        }
    }
}
